name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Generate changelog
        id: changelog
        uses: release-it/release-it@v14.1.0
        with:
          debug: true
          silent: true
          hooks.postversion: |
            echo "Generating changelog..."
            npm run changelog
            git add CHANGELOG.md
            git commit -m "chore(changelog): update changelog for version %s"
            git push origin HEAD:${{ github.ref }}

      - name: Publish package
        uses: JS-DevTools/npm-publish@v3.3.2
        with:
          beforePublishScript: |
            echo "Publishing version $npm_package_version..."
          #   npm run build
          # registry: 'https://registry.npmjs.org'
          # token: ${{ secrets.NPM_AUTH_TOKEN }}
